image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io

build:
  stage: build
  script:
#    - docker info
    - docker build -t docker.io/nollor/budgetapp:$CI_COMMIT_SHORT_SHA .
    - docker push docker.io/nollor/budgetapp:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - main
