stages:
  - build

variables:
  IMAGE_NAME: docker.io/nollor/budgetapp
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker info
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
  # Important : nécessite que le runner soit en mode privilégié
  # Vérifie que ton runner est configuré pour supporter le docker:dind
  tags:
    - docker
  privileged: true
