stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_image:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker info
    - docker build -t nollor/budgetapp:$CI_COMMIT_SHORT_SHA .
    - docker push nollor/budgetapp:$CI_COMMIT_SHORT_SHA
  only:
    - main
