"""Ajout du modèle Budget

Revision ID: 120e3aafb54c
Revises: 811551845400
Create Date: 2024-11-28 14:48:18.916139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120e3aafb54c'
down_revision = '811551845400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budgets')
    # ### end Alembic commands ###
